-- ============================================
-- DISABLE ALL RLS - FINAL FIX
-- ============================================
-- Run this to completely disable RLS on ALL tables

-- Disable RLS on all tables
ALTER TABLE IF EXISTS profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS teachers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS students DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS parents DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS student_parents DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS classes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS subjects DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS class_enrollments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS subject_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS academic_years DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS terms DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS assessments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS assessment_scores DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS report_cards DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS fee_structures DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS fee_payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS announcements DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS attendance DISABLE ROW LEVEL SECURITY;

SELECT 'All RLS policies disabled! App should load fast now.' as message;
